### ISSUE TITLE
"gawk: command not found"

### ISSUE THREAD

**Issue by arrayown** [pothi/wp-in-a-box#63]
When installing Nginx server, I get the following:

```
Installing Nginx Server...
/root/git/wp-in-a-box/scripts/nginx-installation.sh: line 11: gawk: command not found
```

Please make sure "gawk" is in the preinstall packages.

This is happening on Debian 9 stretch VPS with OVH.

Thanks!

**Comment by pothi** [comment]
Hello,

Thanks for notifying about the issue. It is likely my mistake. Also, it's been a while since I tested in Debian 9.

That said, I should've used `awk` instead of using `gawk` directly. Usually, awk is symlinked to gawk internally. Either way, using awk is the correct way. I've updated the repo to use awk instead of gawk directly. Can you please check if the installation goes through now?

**Comment by pothi** [comment]
Hello,

I just tested on Debian 9 hosted in Google Compute Engine. Found a couple of other issues as well. Fixed those now. Please feel free to re-open the issue, if gawk/awk is still an issue in OVH or if you find any other issues.

Thanks again for reporting the bug.
